#!/usr/bin/env bash
set -e

echo files changed: $(git diff $oldrev $newrev --diff-filter=ACDMR --name-only | wc -l)

umask 002

git submodule sync && git submodule update --init --recursive
echo "Restarting python_telegram_bot_template.service"
systemctl --user restart python_telegram_bot_template.service
echo "Restarted"
