#!/usr/bin/env bash
set -e

echo files changed: $(git diff HEAD^ HEAD --diff-filter=ACDMR --name-only | wc -l)

umask 002

echo "Check whether to reinstall python packages"
git diff-tree -r --name-only --no-commit-id HEAD^ HEAD | if grep --quiet "Pipfile.lock"
then
  /home/web_server/.pyenv/versions/XenianBot-vjGaRaxr/bin/pipenv install
fi

echo "Restarting xenian.bot.service"
sudo /home/web_server/admin_services/restart_xenian.bot
echo "Restarted"
