#!/usr/bin/env bash
set -e

echo files changed: $(git diff $oldrev $newrev --diff-filter=ACDMR --name-only | wc -l)

umask 002

git submodule sync && git submodule update --init --recursive
echo "Restarting xenian_bot.service"
systemctl --user restart xenian_bot.service
echo "Restarted"
